#!/bin/bash

# View the difference between the current cluster resources and the configuration generated by kustomize.
# Requires kubectl context to be set.
kustomize diff --context=your-cluster-context ./overlays/prod

# You can also limit it to specific Kubernetes contexts.
kustomize diff --context your-cluster-context ./overlays/dev
